CREATE TABLE users (
    id BIGSERIAL NOT NULL PRIMARY KEY,
    name VARCHAR(50),
    email VARCHAR(100),
    phone VARCHAR(50)
);

CREATE TABLE tickers (
    id BIGSERIAL NOT NULL PRIMARY KEY,
    time TIMESTAMP NOT NULL,
    BTC DECIMAL (10,3),
    ETH DECIMAL (10,3),
    LINK DECIMAL (10,3),
    ADA DECIMAL (10,3)
);
